version: 2

jobs:
  test_grow_method:
    docker:
      - image: golang:1.10.3-alpine3.8
    steps:
      - checkout
      - run: |
          apk add unzip curl
          curl -sS https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
          curl -sSL -o /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.11.8/terraform_0.11.8_linux_amd64.zip
          unzip -q -d /usr/local /tmp/terraform.zip
          dep ensure

workflows:
  version: 2
  test:
    jobs:
      - test_grow_method
