version: 2

jobs:
  build_and_upload:
    docker:
      - image: circleci/golang:1.10.3-stretch
    working_directory: /go/src/github.com/otterley/rollerbot-aws
    steps:
      - checkout
      - run:
          name: Prepare workspace
          command: |
            git fetch --tags
            sudo apt-get update && sudo apt-get -y install python-pip
            sudo pip install awscli >/dev/null
            curl -sS https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
      - run:
          name: Compile and build ZIP files
          command: make zip
      - run:
          name: Upload to S3
          command: make upload
      - save_cache:
          key: gopkg-v1-{{ checksum "Gopkg.lock" }}
          paths:
            - /go/bin/dep
            - vendor


  test_grow_method:
    docker:
      - image: circleci/golang:1.10.3-stretch
    working_directory: /go/src/github.com/otterley/rollerbot-aws
    steps:
      - checkout
      - restore_cache:
          key: gopkg-v1-{{ checksum "Gopkg.lock" }}
      - run:
          name: Prepare workspace
          command: |
            git fetch --tags
            curl -sSL -o /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.11.8/terraform_0.11.8_linux_amd64.zip
            sudo unzip -q -d /usr/bin /tmp/terraform.zip && sudo chmod +x /usr/bin/terraform
            dep ensure
      - run:
          name: Run tests
          command: make test_grow_method

workflows:
  version: 2
  build_test:
    jobs:
      - build_and_upload:
          context: AWS
          filters:
            branches:
              only: master
      - test_grow_method:
          context: AWS
          requires: 
            - build_and_upload
          filters:
            branches:
              only: master
